- name: Bootstrap ipip tunnels for deployment docker swarm cluster in DataLine
#  hosts: dockerhosts*
  hosts: localhost
  user: root
  vars_files:
    - roles/ipip_init/files/var.yml
  roles:
    - ipip_init
