- name: Create Ubuntu instance
  ec2: image={{ image }}
       instance_type={{ instance_type }}
       aws_access_key={{ ec2_access_key }}
       aws_secret_key={{ ec2_secret_key }}
       instance_tags='{ "Name":"{{ hostname }}" }'
       group={{ group }}
       region={{ region }}
       key_name={{ key_pair_name }}
       wait=true
  register: ec2_info

#- debug: var=ec2_info
#- debug: var=item
#  with_items: ec2_info.instance_ids

#- add_host: hostname={{ item.public_ip }} groupname={{ group }}
#  with_items: ec2_info.instances

#- name: wait for instances to listen on port:22
#  wait_for:
#    state=started
#    host={{ ec2_info.instances.public_dns_name }}
#    port=22
#  with_items: ec2_info.instances

