- name: install common packages
  apt: name={{ item }} state=installed
  with_items:
    - python-pip
  tags: install_packages

- name: Upgrade pip
  command: pip install --upgrade pip
  tags: install_packages

- name: Docker-PY
  pip:
    name: "{{ item }}"
  with_items:
  - setuptools
  - docker-py
  tags: install_packages

- name: obsolete container
  docker:
    image: kylemanna/openvpn:latest
    state: stopped

- name: Copy over the openvpn configuration
  synchronize:
    mode: pull
    src: '{{ openvpn_restore_dst }}'
    dest: '{{ openvpn_restore_src }}'
    recursive: yes
    links: yes
    perms: yes
    copy_links: yes
#    delete: yes
  tags: restore_backup_configuration

- name: Start OpenVPN
  command: docker run -v {{ openvpn_volume }}:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
  tags: start_openvpn

