- name: install qemukvm
  apt: name={{ item }} state=installed
  with_items:
    - qemu-kvm
    - qemu-system-arm
    - qemu-system-mips
    - qemu-system-misc
    - qemu-system-ppc
    - qemu-system-sparc
    - qemu-system-x86
